# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/generic
src/reflect
)

#
# contents selected with patternfile ??-header--other-headers
#
set( OTHER_HEADERS
src/unicode/isalphanumeric-utf16-inv.inc
src/unicode/isalphanumeric-utf32-inv.inc
src/unicode/iscapitalized-utf16.inc
src/unicode/iscontrol-utf16.inc
src/unicode/iscontrol-utf32.inc
src/unicode/isdecimaldigit-utf16.inc
src/unicode/isdecimaldigit-utf32.inc
src/unicode/isdecomposable-utf16.inc
src/unicode/isdecomposable-utf32.inc
src/unicode/isdigit-utf16.inc
src/unicode/isdigit-utf32.inc
src/unicode/islegal-utf16.inc
src/unicode/islegal-utf32.inc
src/unicode/isletter-utf16-inv.inc
src/unicode/isletter-utf32-inv.inc
src/unicode/islowercase-utf16.inc
src/unicode/islowercase-utf32.inc
src/unicode/isnonbase-utf16.inc
src/unicode/isnonbase-utf32.inc
src/unicode/isnumeric-utf16.inc
src/unicode/isnumeric-utf32.inc
src/unicode/isprivate-utf16.inc
src/unicode/isprivate-utf32.inc
src/unicode/ispunctuation-utf16.inc
src/unicode/ispunctuation-utf32.inc
src/unicode/isseparator-utf16.inc
src/unicode/issymbol-utf16.inc
src/unicode/issymbol-utf32.inc
src/unicode/isuppercase-utf16.inc
src/unicode/isuppercase-utf32.inc
src/unicode/iswhitespace-utf16.inc
src/unicode/tolower-utf16.inc
src/unicode/tolower-utf32.inc
src/unicode/totitlecase-utf16.inc
src/unicode/totitlecase-utf32.inc
src/unicode/toupper-utf16.inc
src/unicode/toupper-utf32.inc
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-utf-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-utf-include.h
src/reflect/_mulle-utf-provide.h
src/reflect/_mulle-utf-versioncheck.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/mulle-ascii.h
src/mulle-char5.h
src/mulle-char7.h
src/mulle-utf16.h
src/mulle-utf16-string.h
src/mulle-utf32.h
src/mulle-utf32-string.h
src/mulle-utf8.h
src/mulle-utf-convenience.h
src/mulle-utf.h
src/mulle-utf-noncharacter.h
src/mulle-utf-privatecharacter.h
src/mulle-utf-rover.h
src/mulle-utf-scan.h
src/mulle-utf-type.h
)

