#
# This file will be included by cmake/share/Headers.cmake
#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-utf-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-utf-include.h
src/reflect/_mulle-utf-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/mulle-ascii.h
src/mulle-char5.h
src/mulle-char7.h
src/mulle-utf16.h
src/mulle-utf16-string.h
src/mulle-utf32.h
src/mulle-utf32-string.h
src/mulle-utf8.h
src/mulle-utf-convenience.h
src/mulle-utf.h
src/mulle-utf-noncharacter.h
src/mulle-utf-privatecharacter.h
src/mulle-utf-rover.h
src/mulle-utf-scan.h
src/mulle-utf-type.h
)

