#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/mulle-char5.c
src/mulle-char7.c
src/mulle-utf16.c
src/mulle-utf16-string.c
src/mulle-utf32.c
src/mulle-utf32-string.c
src/mulle-utf8.c
src/mulle-utf-convenience.c
src/mulle-utf-noncharacter.c
src/mulle-utf-privatecharacter.c
src/mulle-utf-rover.c
src/mulle-utf-scan.c
)

set( STANDALONE_SOURCES
src/mulle-utf-standalone.c
)
