# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/mulle-ascii.c
src/mulle-char5.c
src/mulle-char7.c
src/mulle-utf16.c
src/mulle-utf16-string.c
src/mulle-utf32.c
src/mulle-utf32-string.c
src/mulle-utf8.c
src/mulle-utf8-string.c
src/mulle-utf-convenience.c
src/mulle-utf-noncharacter.c
src/mulle-utf-privatecharacter.c
src/mulle-utf-rover.c
src/mulle-utf-scan.c
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/mulle-utf-standalone.c
)
