#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/mulle-char5.c
src/mulle-char7.c
src/mulle-utf16.c
src/mulle-utf16-string.c
src/mulle-utf32.c
src/mulle-utf32-string.c
src/mulle-utf8.c
src/mulle-utf-convenience.c
src/mulle-utf-is-alphanumeric.c
src/mulle-utf-is-capitalized.c
src/mulle-utf-is-control.c
src/mulle-utf-is-decimaldigit.c
src/mulle-utf-is-decomposable.c
src/mulle-utf-is-legalcharacter.c
src/mulle-utf-is-letter.c
src/mulle-utf-is-lowercase.c
src/mulle-utf-is-newline.c
src/mulle-utf-is-nonbase.c
src/mulle-utf-is-noncharacter.c
src/mulle-utf-is-nonpercentescape.c
src/mulle-utf-is-privatecharacter.c
src/mulle-utf-is-punctuation.c
src/mulle-utf-is-symbol.c
src/mulle-utf-is-uppercase.c
src/mulle-utf-is-validurlfragment.c
src/mulle-utf-is-validurlhost.c
src/mulle-utf-is-validurlpassword.c
src/mulle-utf-is-validurlpath.c
src/mulle-utf-is-validurlquery.c
src/mulle-utf-is-validurlscheme.c
src/mulle-utf-is-validurluser.c
src/mulle-utf-is-whitespace.c
src/mulle-utf-is-whitespaceornewline.c
src/mulle-utf-rover.c
src/mulle-utf-scan.c
src/mulle-utf-standalone.c
src/mulle-utf-tolower.c
src/mulle-utf-toupper.c
)
